### ISSUE TITLE
Clarifying the Impact of Mitochondrial Transcripts on snRNA-seq Data Quality

### ISSUE THREAD

**Issue by jma1991** [OSCA-source/OSCA.advanced#16]
Hello,

I'm seeking clarification rather than reporting an issue, and I'm happy to move this discussion to the Bioconductor support forum if that's more suitable.

The section on single nuclei RNA-seq processing mentions:

"High-quality nuclei should not contain any mitochondrial transcripts; the presence of any mitochondrial counts in a library indicates that the removal of the cytoplasm was not complete, possibly introducing irrelevant heterogeneity in downstream analyses."

Does this heterogeneity exclusively stem from mitochondrial transcripts? If that's the case, would removing these transcripts from the count matrix eliminate the concern, or are there additional factors that might affect the integrity of the analysis?

**Comment by alanocallaghan** [comment]
This isn't exactly my area of expertise, but the assumption is that given nuclei shouldn't contain mitochondria, the presence of mitochondrial transcripts indicates contamination of some sort. Obviously removing mitochondrial transcripts would remove the mitochondrial contamination, but it's very likely that non-mitochondrial transcripts have also contaminated the data through the same mechanism.

Or, to directly answer the questions:
> Does this heterogeneity exclusively stem from mitochondrial transcripts? 

This is very unlikely.

> If that's the case, would removing these transcripts from the count matrix eliminate the concern, or are there additional factors that might affect the integrity of the analysis?

If it was the case, then maybe, but it is not.

**Comment by NadineBestard** [comment]
Interesting thought in that regard, is that the cell's cytoplasmic RNA may stick to the nuclei when they are extracted. This would mean that some of the cytoplasmic RNA is probably contamination from other cells (ambient RNA), but most of the cytoplasmic RNA comes from the cell of interest.  Most nuclei applications are performed to explore hard-to-dissociate cells,  meaning that "the removal of the cytoplasm was not complete" may not be per se a downside, it is giving you a bit more info about that cell's transcriptome. 

I also wanted to point out that the nuclei datasets I have seen always had a fair amount of mitochondrial genes. So even though it sounds good in theory I think this statement may be an overestimation of how "clean" these nuclei come up in practice.

**Comment by jma1991** [comment]
> Interesting thought in that regard, is that the cell's cytoplasmic RNA may stick to the nuclei when they are extracted. This would mean that some of the cytoplasmic RNA is probably contamination from other cells (ambient RNA), but most of the cytoplasmic RNA comes from the cell of interest. Most nuclei applications are performed to explore hard-to-dissociate cells, meaning that "the removal of the cytoplasm was not complete" may not be per se a downside, it is giving you a bit more info about that cell's transcriptome.
> 
> I also wanted to point out that the nuclei datasets I have seen always had a fair amount of mitochondrial genes. So even though it sounds good in theory I think this statement may be an overestimation of how "clean" these nuclei come up in practice.

Agreed, there always seems to be a few percent attribute to MT transcripts. If cytoplasmic RNA from the cell or the ambient pool is likely (as signalled by MT contamination) it's probably not worth proceeding with the analysis. I fear that the heterogeneity in contamination across samples or replicates might produce cells from the same cell type with slightly different transcriptome profiles making them appear distinct.

**Comment by LTLA** [comment]
FWIW the intention of the outlier-based threshold is to remove nuclei with "higher-than-expected" mitochondrial proportions. It is less concerned with an absolute threshold, analogous to the logic behind the outlier-based QC filtering on whole-cell transcriptomes in regular scRNA-seq. 

For most snRNA-seq applications, I daresay it doesn't matter that there is cytoplasmic contamination. I don't recall seeing many papers where the explicit goal is to study nuclear transcripts, and even in the studies that generate data using both technologies, the aim is often to demonstrate how _similar_ they are, rather than focusing on the differences. My impression is that most people generate snRNA-seq because whole-cell dissociation is too hard experimentally, e.g., anything to do with neurons.

So, in this type of analysis, the goal of QC is not to remove cells with contamination, because we don't really care about that - but instead, to remove cells that have unusually high levels of contamination relative to other cells in the same dataset. This aims to avoid artificial heterogeneity from incomplete stripping for a subset of cells. Of course, there's a whole set of other caveats that come with this filtering (see the book) so one can debate how successful/necessary this strategy really is; but we don't try to claim that there's some magic number above which the nuclei can be considered "high-quality".
